export const cardList = [
    {
        type: 'taocan',
        title: '羊汤',
        num: '2',
        price: '2.00',
        desc: '描述信息',
    },
    {
        type: 'taocan',
        title: '鸡汤',
        num: '2',
        price: '2.00',
        desc: '描述信息',
    },
    {
        type: 'taocan',
        title: '驴头火烧',
        num: '2',
        price: '2.00',
        desc: '描述信息',
    },
    {
        type: 'taocan',
        title: '麻辣拌',
        num: '2',
        price: '2.00',
        desc: '描述信息',
    },
    {
        type: 'taocan',
        title: '麻辣香锅',
        num: '2',
        price: '2.00',
        desc: '描述信息',
    },
    {
        type: 'xiaochi',
        title: '辣条',
        num: '2',
        price: '2.00',
        desc: '描述信息',
    },
    {
        type: 'xiaochi',
        title: '薯片',
        num: '2',
        price: '2.00',
        desc: '描述信息',
    },
    {
        type: 'xiaochi',
        title: '饼干',
        num: '2',
        price: '2.00',
        desc: '描述信息',
    },
    {
        type: 'yinliao',
        title: '可乐',
        num: '2',
        price: '2.00',
        desc: '描述信息',
    },
    {
        type: 'yinliao',
        title: '雪碧',
        num: '2',
        price: '2.00',
        desc: '描述信息',
    },
    {
        type: 'yinliao',
        title: '酸梅汁',
        num: '2',
        price: '2.00',
        desc: '描述信息',
    },
    {
        type: 'youhui',
        title: '资本家没有优惠',
        num: '1',
        price: '10000000.00',
        desc: '描述信息',
    },
    {
        type: 'youhui',
        title: '打工人工资要低',
        num: '2',
        price: '2.00',
        desc: '描述信息',
    },
    {
        type: 'youhui',
        title: '有利于社会发展',
        num: '2',
        price: '2.00',
        desc: '描述信息',
    },
    {
        type: 'lingshi',
        title: '辣条11',
        num: '2',
        price: '2.00',
        desc: '描述信息',
    },
    {
        type: 'lingshi',
        title: '薯片11',
        num: '2',
        price: '2.00',
        desc: '描述信息',
    },
    {
        type: 'lingshi',
        title: '饼干11',
        num: '2',
        price: '2.00',
        desc: '描述信息',
    },
];
